// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_az_Sqp-Rnk0MqNH58fzcSEsPPAoG4Mw',
    appId: '1:90339579608:web:86a476d2ad87ad0ff229ad',
    messagingSenderId: '90339579608',
    projectId: 'fitness-app-769a6',
    authDomain: 'fitness-app-769a6.firebaseapp.com',
    storageBucket: 'fitness-app-769a6.firebasestorage.app',
    measurementId: 'G-X1DBPL281R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu3xqVd4Id2LeE0c8Icm_k6NpNadA18C0',
    appId: '1:90339579608:android:daf0667ccf1bbacef229ad',
    messagingSenderId: '90339579608',
    projectId: 'fitness-app-769a6',
    storageBucket: 'fitness-app-769a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0ODsIkeFOFoU-H0x86eB_OvM0WDKkB8',
    appId: '1:90339579608:ios:f83c8e9fb1984c27f229ad',
    messagingSenderId: '90339579608',
    projectId: 'fitness-app-769a6',
    storageBucket: 'fitness-app-769a6.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu0ODsIkeFOFoU-H0x86eB_OvM0WDKkB8',
    appId: '1:90339579608:ios:f83c8e9fb1984c27f229ad',
    messagingSenderId: '90339579608',
    projectId: 'fitness-app-769a6',
    storageBucket: 'fitness-app-769a6.firebasestorage.app',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_az_Sqp-Rnk0MqNH58fzcSEsPPAoG4Mw',
    appId: '1:90339579608:web:ddef12b020555b4bf229ad',
    messagingSenderId: '90339579608',
    projectId: 'fitness-app-769a6',
    authDomain: 'fitness-app-769a6.firebaseapp.com',
    storageBucket: 'fitness-app-769a6.firebasestorage.app',
    measurementId: 'G-TPT4Y99ZR8',
  );
}
